### ISSUE TITLE
メガガイア bot broken

### ISSUE THREAD

**Issue by konafx** [damphuge/candle-nightshade#23]
```
(node:464877) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'time' of undefined
    at constructResText (/home/konafx/.ghq/github.com/damphuge/candle-nightshade/mega_osmosis.js:53:88)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:464877) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:464877) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by GGnara** [comment]
メガガイアのＨＰの仕様が変わったので凍結
